name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Code build, lint and tests
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: ENV=ci make start
      - name: Code Analyze
        run: ENV=ci make cs ca
      - name: Tests
        run: make ENV=ci test
