name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Code build, lint and tests
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: make start
      - name: Code Analyze
        run: make cs ca
#      - name: Tests
#        run: make env=ci xon;make env=ci test
#      - name: DB Schema validation
#        run: make env=ci schema-validate
#      - name: ARTIFACT
#        run: make env=ci artifact
